import { mkdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname } from 'node:path';

export const generateFileUtil = async (
  file: string,
  data: string | Buffer<ArrayBuffer>,
  options?: { overwrite?: boolean; header?: boolean },
): Promise<void> => {
  const folder = dirname(file);
  const overwriteOpt = options?.overwrite ?? false;
  const headerOpt = options?.header ?? true;

  if (!overwriteOpt && existsSync(file)) {
    return;
  }

  const header = headerOpt
    ? `// AUTO-GENERATED FILE — DO NOT EDIT
// Generated by @amiral-corelab/acl tooling.
`
    : '';

  await mkdir(folder, { recursive: true });
  await writeFile(file, typeof data === 'string' ? `${header}${data}` : data, {
    encoding: typeof data === 'string' ? 'utf8' : undefined,
  });
};
