// AUTO-GENERATED FILE — DO NOT EDIT
// Generated by @amiral-corelab/acl tooling.

/* eslint-disable */
/* stylelint-disable */
export type IconType =
  | 'brand-acl'
  | 'input-check-mark'
  | 'input-indeterminate-mark'
  | 'shape-circle';
