name: 📥 Figma Artifacts · Download

runs:
  using: 'composite'
  steps:
    - name: 📥 Figma Artifacts · Download
      uses: actions/download-artifact@v7
      with:
        name: artifacts-figma
        path: artifacts/figma
