// AUTO-GENERATED FILE — DO NOT EDIT
// Generated by @amiral-corelab/acl tooling.

/* eslint-disable */
/* stylelint-disable */
export const iconConstant = [
  'brand-acl',
  'input-check-mark',
  'input-indeterminate-mark',
  'input-radio-mark',
  'shape-circle',
];
