name: CI - DEV

on:
  pull_request:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      # Variables d’environnements classiques
      FIGMA_ACCESS_TOKEN: ${{ secrets.FIGMA_ACCESS_TOKEN }}
      FIGMA_FILE_KEY: ${{ secrets.FIGMA_FILE_KEY }}
      FIGMA_FILE_SPEC_NODE_ID: ${{ secrets.FIGMA_FILE_SPEC_NODE_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: npm i

      - name: Prepare Storybook
        run: npm run acl:storybook-ci

      - name: Run tests + API scripts
        run: ci:check
